### ISSUE TITLE
Access rights to create a project

### ISSUE THREAD

**Issue by rouson** [gklimowicz/j3-papers#1]
@gklimowicz when I click the Projects link, I get a page that lets me view exist projects or link a project, but I don't get the green "New project" button.  Possibly that requires certain access rights?  There's no rush on this. My goal is to use it during the next meeting.  The setup is sufficiently simple that I can just set it up at the meeting, but if you know what to do, feel free to grant me the rights and I'll get a start.

**Comment by gklimowicz** [comment]
I don't use GitHub for a lot of collaborative work, so if there is a way to give you repo admin rights, I haven't found it. It might be a thing that "organizations" get if you have the right flavor of "organization". Advice is welcome...

**Comment by rouson** [comment]
@gklimowicz I think I see now that it wasn't related to access rights.  My experience is with GitHub Projects "Classic," where I'd see a green "New project" button on the repository.   Apparently GitHub only allows the use of the Classic version of Projects on repositories that already have one Classic Project.  With the new GitHub Projects, it appears the user creates the project under their own account and think links a repository to it.  The overall look of the project board is different too.  At first glance, I don't like the new approach so I'll have to evaluate its utility.  We can close this issue for now.

**Comment by gklimowicz** [comment]
I will leave this in your capable hands. Thanks.
